spring:
  datasource:
    url: jdbc:h2:file:./yfckevinDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    initialize: true
    username: chenyifan
    password: password
  h2:
    console:
      enabled: true
      path: /console
      settings.web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
